### ISSUE TITLE
scp commands truncated in SCINet File Transfer guide

### ISSUE THREAD

**Issue by nathanweeks** [USDA-ARS-GBRU/scinet-site#155]
The formatting truncates the scp commands in https://scinet.usda.gov/guide/file-transfer/#small-data-transfer-using-scp

**Comment by davidorman** [comment]
This template is fixed width and doesnt deal with long lines of code well.

going to try and make the lines shorter so its happier, it not clear to me how to make the template better.

**Comment by davidorman** [comment]
the lines all fit now but still dont look great, hopefully a future theme update will clean this up.
